spring.application.name=mi-negocio123
spring.datasource.url=jdbc:postgresql://localhost:5432/minegocio_db
spring.datasource.username=postgres
spring.datasource.password=admin123
spring.jpa.hibernate.ddl-auto=create